var isLoggedIn = false;
var customerId = "";
var customerName = "";
var customerEmail = "";
var customerPhone = "";
var customerDOB;
var customerStreet = "";
var customerCity = "";
var customerApartmentNumber = 0;
var customerPassword = "";